/*
 * Copyright (c) 2026 Pranaah Electronics Pvt Ltd. All rights reserved.
 *
 * This source code and all associated files are the proprietary and confidential
 * property of Pranaah Electronics Pvt Ltd. Unauthorized copying, modification,
 * distribution, or use of this software, via any medium, is strictly prohibited
 * without the express written permission of Pranaah Electronics Pvt Ltd.
 */

package com.wearables.consent.domain.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * Stores a user's push notification and quiet-hours preferences.
 *
 * <p>One row per user. The row is created on first update; read before create
 * returns sensible defaults (push on, DND off, all alert types on).
 */
@Entity
@Table(name = "notification_preferences", uniqueConstraints = {
        @UniqueConstraint(name = "uq_notif_pref_user_id", columnNames = "user_id")
})
@Getter @Setter @Builder
@NoArgsConstructor @AllArgsConstructor
public class NotificationPreference {

    @Id
    private UUID id;

    @Column(name = "user_id", nullable = false, unique = true)
    private UUID userId;

    /** Master push-notification opt-in. When false, no notifications are sent. */
    @Column(name = "push_enabled", nullable = false)
    private boolean pushEnabled;

    /** When true, pushes are suppressed between quietHoursStart and quietHoursEnd. */
    @Column(name = "quiet_hours_enabled", nullable = false)
    private boolean quietHoursEnabled;

    /** Local time (HH:mm) at which quiet hours begin, e.g. "22:00". */
    @Column(name = "quiet_hours_start", length = 5)
    private String quietHoursStart;

    /** Local time (HH:mm) at which quiet hours end, e.g. "07:00". */
    @Column(name = "quiet_hours_end", length = 5)
    private String quietHoursEnd;

    /**
     * Do-Not-Disturb override. When true, all notifications are suppressed
     * regardless of other settings. Mirrors system DND on the device.
     */
    @Column(name = "dnd_enabled", nullable = false)
    private boolean dndEnabled;

    /** Health alerts generated by decision-service (e.g. high heart rate). */
    @Column(name = "alerts_enabled", nullable = false)
    private boolean alertsEnabled;

    /** Medication / activity reminder notifications. */
    @Column(name = "reminders_enabled", nullable = false)
    private boolean remindersEnabled;

    /** Promotional and marketing messages. */
    @Column(name = "marketing_enabled", nullable = false)
    private boolean marketingEnabled;

    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;
}
